### PR TITLE
New features & restructuring

### PR DESCRIPTION
**Pull request by esbena**
This pull request contains features that have piled up through the years in my research group (http://casa.au.dk/).

Besides a large restructuring of the entire project (and a resulting bad diff), the main new features include:

- fixes for #12, #22
- tests and examples (run ./test.sh)
- `--dir DIR`: the content of the `DIR` directory will be reduced: files/directories will be deleted and .js-files will be reduced as usual. Note that .js files are not required to be present at all, so JS Delta is capable of finding an abitrary subset of files that satisfy a predicate.
- `--optimize`: the closure compiler will perform its optimizations on the reduced JavaScript files. This can lead to significantly smaller files than otherwise, especially if it is able to inline function calls.
- `--out FILE`: the reduced file (or directory) will be copied to `DIR`
- README.md has been updated with the new features

This has been tested on Ubuntu and OSX, with node 5 and 6

### CODE REVIEW

**Comment by msridhar** [comment]
Hi @esbena this looks great!  Quick question: is Node.js 4 still supported?  I just ran the tests and they all passed.  I want to confirm since 4.x is still the "stable" version.

**Comment by esbena** [comment]
@msridhar good catch.

Node v4 should still be supported, we did not do anything deliberate to break it. 

I have now successfully run ./test.sh for Node v1, v2, v3, v4 (using the most recent nvm versions)*. I belive the implementation is stable across node versions.


*: although I did not do `npm install` for each new node version.

**Comment by msridhar** [comment]
I am happy to merge this, but I'd like @xiemaisi to chime in first with a LGTM, if possible.

**Comment by esbena** [comment]
@msridhar I have  added the travis support from #24 to this pull request.

**Comment by msridhar** [comment]
I chatted with @xiemaisi and we're fine with merging this PR.  In fact, @esbena if you're up for it, we'd like to make you a maintainer of this project with commit access.  The only thing is I think we need a signed CLA in place, even to merge a PR of this size.  This is the form:

http://wala.sourceforge.net/wiki/index.php/Contributor_License_Agreement

@esbena are you able to sign this form and scan and email me a copy?  You may need to check with the university.

**Comment by msridhar** [comment]
Thanks again!

**Comment by xiemaisi** [comment]
LGTM found [a few minor things](https://lgtm.com/projects/g/wala/jsdelta/alerts/) that may be worth fixing.

**Comment by msridhar** [comment]
@xiemaisi cool!  where is the auto-generated pull request to fix the issues? 😄

**Comment by xiemaisi** [comment]
Heh, not quite done yet, that.

I've enabled PR integration, so assuming it works we'll get LGTM posting alerts on future PRs.

**Pull request merged**
