### PR TITLE
Use espree to support latest ecmascript syntax.

### PR DESCRIPTION
**Pull request by ribrdb**

### CODE REVIEW

**Comment by msridhar** [comment]
@ribrdb thanks for the contribution!  I've enabled CI via GitHub Actions now.  Could you add a couple of tests that use the latest ECMAScript syntax?  `test.sh` is the test script, and you can see the existing tests under `examples`.

**Comment by ribrdb** [comment]
Does this look ok? It looks like you have tests set to run on node 12, 14, and 16. But the nullish coalescing operator isn't supported with node 12.

**Comment by msridhar** [comment]
@ribrdb I'm ok with only running tests on 14 and 16.  Do you want to make that change?

**Review by msridhar — APPROVED** [review]

**Comment by msridhar** [comment]
Thanks again!

**Comment by ribrdb** [comment]
Thanks for a great tool!

**Pull request merged**
